#!/bin/sh -l
# Run 
#SBATCH --job-name=logreg.jl
#SBATCH --output=logreg.out
#SBATCH --nodes=10
#SBATCH --ntasks-per-node=1
#SBATCH --time=6000:00
#SBATCH --cpus-per-task=3
#SBATCH --partition=rome16q

# Remember to load eX3 modules:
# module use /cm/shared/ex3-modules/0.6.1/modulefiles
# module load slurm/20.02.6
# module load openmpi-4.0.5

export JULIA_DEPOT_PATH="/home/albin/.julia/"
date
filename=/home/albin/.julia/dev/CodedComputing/src/pca/logreg.jl
execname=/home/albin/julia/julia-1.6.1/bin/julia

# rcv1
input_file=/home/albin/traces/rcv1/rcv1_shuffled.h5
output_directory=/home/albin/traces/rcv1/rome16q/210911_4/

inputdataset=X
npasses=15000

lambda=$(python3 -c 'print(1/697641)')
nthreads=3
# nwait_all=( 9 6 3)
nwait_all=( 9)
nsubpartitions_all=( 10)
# nsubpartitions_all=( 1 2 5 10 40 80 120 160 240 320)
# nsubpartitions_all=( 10 14 20 40 80 160 240 320 2304)
stepsize=10.0

nslow=3
slowprob=0.1

for i in {1..1}
do
    for nsubpartitions in ${nsubpartitions_all[@]}
    do
        # niterations=1000
        niterations=$(($npasses * $nsubpartitions))
        # nwait=10
        # echo "[SAG (--nostale)] nsubpartitions: ${nsubpartitions}, nwait: ${nwait}, niterations: $niterations, stepsize: $stepsize"
        # /opt/amazon/openmpi/bin/mpirun -n "$SLURM_NTASKS" julia --project "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --inputdataset ${inputdataset} --stepsize ${stepsize} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --ncomponents ${ncomponents} --iteratedataset ${iteratedataset} --saveiterates --variancereduced --nostale
        # echo "[SGD] nsubpartitions: ${nsubpartitions}, nwait: ${nwait}, niterations: $niterations"
        # /opt/amazon/openmpi/bin/mpirun -n "$SLURM_NTASKS" julia --project "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --inputdataset ${inputdataset} --stepsize ${stepsize} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --ncomponents ${ncomponents} --iteratedataset ${iteratedataset} --saveiterates

        for nwait in ${nwait_all[@]}
        do
            # 1000 genomes (entire dataset, fully shuffled)
            # input_file=/home/albin/traces/1000genomes-matrix/1000genomes-matrix.h5
            echo "[DSAG, 1000 genomes] nsubpartitions: ${nsubpartitions}, nwait: ${nwait}, niterations: $niterations"

            # with nslow
            ## load-balanced
            srun -x UCX_ERROR_SIGNALS="SIGILL,SIGBUS,SIGFPE" ${execname} --project --threads ${nthreads} "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --inputdataset ${inputdataset} --stepsize ${stepsize} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --saveiterates --loadbalance --nslow ${nslow} --variancereduced

            ## unbalanced
            srun -x UCX_ERROR_SIGNALS="SIGILL,SIGBUS,SIGFPE" ${execname} --project --threads ${nthreads} "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --inputdataset ${inputdataset} --stepsize ${stepsize} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --saveiterates --nslow ${nslow} --variancereduced

            # # default
            # ## load-balanced
            # srun -x UCX_ERROR_SIGNALS="SIGILL,SIGBUS,SIGFPE" ${execname} --project --threads ${nthreads} "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --inputdataset ${inputdataset} --stepsize ${stepsize} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --saveiterates --loadbalance --variancereduced
            
            # ## unbalanced
            # srun -x UCX_ERROR_SIGNALS="SIGILL,SIGBUS,SIGFPE" ${execname} --project --threads ${nthreads} "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --inputdataset ${inputdataset} --stepsize ${stepsize} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --saveiterates --variancereduced

            # # with slowprob.
            # ## load-balanced
            # srun -x UCX_ERROR_SIGNALS="SIGILL,SIGBUS,SIGFPE" ${execname} --project --threads ${nthreads} "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --inputdataset ${inputdataset} --stepsize ${stepsize} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --saveiterates --loadbalance --slowprob ${slowprob} --variancereduced

            # ## unbalanced
            # srun -x UCX_ERROR_SIGNALS="SIGILL,SIGBUS,SIGFPE" ${execname} --project --threads ${nthreads} "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --inputdataset ${inputdataset} --stepsize ${stepsize} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --saveiterates --slowprob ${slowprob} --variancereduced

            # # with nslow and slowprob.
            # ## load-balanced
            # srun -x UCX_ERROR_SIGNALS="SIGILL,SIGBUS,SIGFPE" ${execname} --project --threads ${nthreads} "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --inputdataset ${inputdataset} --stepsize ${stepsize} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --saveiterates --loadbalance --nslow ${nslow} --slowprob ${slowprob} --variancereduced

            # ## unbalanced
            # srun -x UCX_ERROR_SIGNALS="SIGILL,SIGBUS,SIGFPE" ${execname} --project --threads ${nthreads} "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --inputdataset ${inputdataset} --stepsize ${stepsize} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --saveiterates --nslow ${nslow} --slowprob ${slowprob} --variancereduced

            # # 1000 genomes dense-equivalent matrix
            # input_file=/home/albin/traces/1000genomes-dense-equiv-matrix/1000genomes-dense-equiv-matrix.h5
            # echo "[DSAG, 1000 genomes dense equiv.] nsubpartitions: ${nsubpartitions}, nwait: ${nwait}, niterations: $niterations"        
            # # --saveiterates
            # srun ${execname} --project "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --inputdataset ${inputdataset} --stepsize ${stepsize} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --ncomponents ${ncomponents} --iteratedataset ${iteratedataset} --variancereduced
        done
    done
done

# # GD
# stepsize=10.0
# nsubpartitions=1
# nwait=9
# # niterations=$(($npasses * $nsubpartitions))
# niterations=400
# echo "[GD] nsubpartitions: ${nsubpartitions}, nwait: ${nwait}, niterations: $niterations"
# srun -x UCX_ERROR_SIGNALS="SIGILL,SIGBUS,SIGFPE" ${execname} --project --threads ${nthreads} "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --inputdataset ${inputdataset} --stepsize ${stepsize} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --saveiterates

echo "Done"