#!/bin/sh -l
# Run 
#SBATCH --job-name=logreg.jl
#SBATCH --output=logreg.out
#SBATCH --nodes=5
#SBATCH --ntasks-per-node=10
#SBATCH --time=6000:00
#SBATCH --cpus-per-task=3
# #SBATCH --overcommit
# #SBATCH --oversubscribe
#SBATCH --partition=rome16q

# Remember to load eX3 modules:
# module use /cm/shared/ex3-modules/latest/modulefiles
# module load slurm/20.02.7
# module load openmpi-4.0.5

export JULIA_DEPOT_PATH="/home/albin/.julia/"
date
filename=/home/albin/.julia/dev/CodedComputing/src/pca/logreg.jl
execname=/home/albin/julia/julia-1.7.0-beta4/bin/julia

# # rcv1
# input_file=/home/albin/traces/rcv1/rcv1_shuffled.h5
# output_directory=/home/albin/traces/rcv1/rome16q/210911_9/

# # covtype
# input_file=/home/albin/traces/covtype/covtype.h5
# output_directory=/home/albin/traces/covtype/rome16q/211016_1/ # latency_increase_factor = 1
# lambda=$(python3 -c 'print(1/581012)')

# higgs
input_file=/home/albin/traces/higgs/higgs.h5
# output_directory=/home/albin/traces/higgs/rome16q/211018_2/ # latency_increase_factor = 1
# output_directory=/home/albin/traces/higgs/rome16q/211018_3/ # latency_increase_factor = 10
# output_directory=/home/albin/traces/higgs/rome16q/211018_4/ # latency_increase_factor = 1
# output_directory=/home/albin/traces/higgs/rome16q/211018_5/ # latency_increase_factor = 10
# output_directory=/home/albin/traces/higgs/rome16q/211019_1/ # latency_increase_factor = 1
# output_directory=/home/albin/traces/higgs/rome16q/211019_2/ # latency_increase_factor = 1
# output_directory=/home/albin/traces/higgs/rome16q/211020_1/ # latency_increase_factor = 1
# output_directory=/home/albin/traces/higgs/rome16q/211021_1/ # latency_increase_factor = 1
# output_directory=/home/albin/traces/higgs/rome16q/211021_2/ # latency_increase_factor = 1
output_directory=/home/albin/traces/higgs/rome16q/211021_3/ # latency_increase_factor = 1
lambda=$(python3 -c 'print(1/11000000)')

# parameters
inputdataset=X
npasses=500
nthreads=3
let nworkers=$SLURM_NTASKS-1
profilerwindowsize=10
# nwait_all=( 10 40 49)
nwait_all=( 20)
nsubpartitions_all=( 10)
stepsize=0.25
lbminimprovement=0.95
# lbminimprovement=0.98
profilerminsamples=100

# working set
# nwait 35
# stepsize 1.0
# nsubpartitions 5

# unused
nslow=0
slowprob=0

for i in {1..5}
do
    for nsubpartitions in ${nsubpartitions_all[@]}
    do
        niterations=$(($npasses * $nsubpartitions))
        for nwait in ${nwait_all[@]}
        do
            echo "[1000 genomes] nsubpartitions: ${nsubpartitions}, nwait: ${nwait}, niterations: $niterations"

            # DSAG
            ## load-balanced
            date
            srun -x UCX_ERROR_SIGNALS="SIGILL,SIGBUS,SIGFPE" ${execname} --project --threads ${nthreads} "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --randomseed ${i} --inputdataset ${inputdataset} --stepsize ${stepsize} --lambda ${lambda} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --saveiterates --loadbalance --lbminimprovement ${lbminimprovement} --profilerwindowsize ${profilerwindowsize} --profilerminsamples ${profilerminsamples} --nslow ${nslow} --variancereduced

            ## unbalanced
            srun -x UCX_ERROR_SIGNALS="SIGILL,SIGBUS,SIGFPE" ${execname} --project --threads ${nthreads} "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --randomseed ${i} --inputdataset ${inputdataset} --stepsize ${stepsize} --lambda ${lambda} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --saveiterates --nslow ${nslow} --variancereduced

            # SAG
            if ((nwait < nworkers))
            then
                ## load-balanced
                date
                srun -x UCX_ERROR_SIGNALS="SIGILL,SIGBUS,SIGFPE" ${execname} --project --threads ${nthreads} "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --randomseed ${i} --inputdataset ${inputdataset} --stepsize ${stepsize} --lambda ${lambda} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --saveiterates --loadbalance --lbminimprovement ${lbminimprovement} --profilerwindowsize ${profilerwindowsize} --profilerminsamples ${profilerminsamples} --nslow ${nslow} --variancereduced --nostale

                ## unbalanced
                srun -x UCX_ERROR_SIGNALS="SIGILL,SIGBUS,SIGFPE" ${execname} --project --threads ${nthreads} "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --randomseed ${i} --inputdataset ${inputdataset} --stepsize ${stepsize} --lambda ${lambda} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --saveiterates --nslow ${nslow} --variancereduced --nostale        
            fi

            # SGD
            ## load-balanced
            date
            srun -x UCX_ERROR_SIGNALS="SIGILL,SIGBUS,SIGFPE" ${execname} --project --threads ${nthreads} "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --randomseed ${i} --inputdataset ${inputdataset} --stepsize ${stepsize} --lambda ${lambda} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --saveiterates --loadbalance --lbminimprovement ${lbminimprovement} --profilerwindowsize ${profilerwindowsize} --profilerminsamples ${profilerminsamples} --nslow ${nslow}

            ## unbalanced
            srun -x UCX_ERROR_SIGNALS="SIGILL,SIGBUS,SIGFPE" ${execname} --project --threads ${nthreads} "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --randomseed ${i} --inputdataset ${inputdataset} --stepsize ${stepsize} --lambda ${lambda} --nsubpartitions ${nsubpartitions} --nwait ${nwait} --niterations ${niterations} --saveiterates --nslow ${nslow}
        done
    done
done

# GD
nsubpartitions=1
stepsize=1.0
npasses=1000
nwait=${nworkers}
niterations=$(($npasses * $nsubpartitions))
echo "[GD] nsubpartitions: ${nsubpartitions}, nwait: ${nwait}, niterations: $niterations"
date
srun -x UCX_ERROR_SIGNALS="SIGILL,SIGBUS,SIGFPE" ${execname} --project --threads ${nthreads} "${filename}" "${input_file}" "${output_directory}/output $(date).h5" --inputdataset ${inputdataset} --stepsize ${stepsize} --lambda ${lambda} --nsubpartitions ${nsubpartitions} --nwait ${nworkers} --niterations ${niterations} --saveiterates

echo "Done"